# ./ docker.compose.yml

version: '3.8'

services:
  websocket:
    container_name: websocket_server_1
    build: .
    ports:
      - "${PORT_SERVER}:${PORT_SERVER}"
    environment:
      AUTH_TOKEN: ${AUTH_TOKEN}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
