worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream websocket_servers {
        server websocket_server_1:3000 max_fails=3 fail_timeout=30s;  # Ajusta según tus necesidades
        server websocket_server_2:3001 max_fails=3 fail_timeout=30s;  # Ajusta según tus necesidades
        keepalive 32;  # Mantener conexiones abiertas para mejorar la eficiencia
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://websocket_servers;  # Redirigir a los servidores WebSocket
            proxy_http_version 1.1;  # Usar HTTP/1.1 para WebSockets
            proxy_set_header Upgrade $http_upgrade;  # Soporte para WebSocket
            proxy_set_header Connection "upgrade";  # Soporte para WebSocket
            proxy_set_header Host $host;  # Mantener el encabezado Host
            proxy_set_header X-Real-IP $remote_addr;  # Pasar la IP real del cliente
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Encabezado X-Forwarded-For

            proxy_read_timeout 86400;
            proxy_send_timeout 86400;
        }
    }
}
